### ISSUE TITLE
Two asd files giving a warning

### ISSUE THREAD

**Issue by Slids** [darabi/cl-base64#1]
;   System definition file #P"/home/*/quicklisp/dists/quicklisp/software/cl-base64-20150923-git/cl-base64.asd" contains definition for system "c\
l-base64-tests". Please only define "cl-base64" and secondary systems with a name starting with "cl-base64/" (e.g. "cl-base64/test") in that file.

**Comment by darabi** [comment]
Thank you for reporting this but unfortunately, I'm not the maintainer of cl-base64. The single commit which you see in this fork solves the problem which you see, so you could just clone this repo into your local-projects and use it.

In the meantime, I will try to contact the maintainer and get back to you here.

**Comment by darabi** [comment]
I contacted the maintainer who fixed the issue with this commit:

http://git.kpe.io/?p=cl-base64.git;a=commitdiff;h=639eae034168813cf2b981ef1f6efe373a4adf6b

So the next Quicklisp release will pull in that change. Until then, you can

```
cd ~/quicklisp/local-projects/
git clone http://git.kpe.io/cl-base64.git
```
and use the current master.

HTH
